LG-Uplus-Movie-SNS-PICKY/PICKY-FE

.github/workflows/main.yml
README.md

feat: 프론트엔드 CI/CD 구축
// close #이슈번호
1. 프론트엔드 CO/CD
- 
- 
-

feat: 프론트엔드 CI/CD 구축

---

.github/workflows/main.yml

FrontEnd main branch CI/CD
[FEAT] main branch CI/CD 구축
1. main branch CI/CD 구축
- 
- 
-

[FEAT] main branch CI/CD 구축

---

src/stories/button/Button.stories.ts
src/stories/genre-tab/GenreTab.stories.ts
src/stories/genre-tab/index.styles.tsx
src/stories/genre-tab/index.tsx

[CPG-98](https://multicampusuplus.atlassian.net/browse/CPG-98)
// close #14
1. 영화 장르 버튼 추가
2. Rectangle/Round 구분
- 
-

[FEAT] 스토리북 장르 버튼 추가

---

.github/ISSUE_TEMPLATE/issue-form.yml

[]() [FEAT] 지라 협업 연동 이슈 템플릿
// close #이슈번호
1.  지라 협업 연동 이슈 템플릿
-  지라 협업 연동 이슈 템플릿
- 
-

[FEAT] 지라 협업 연동 이슈 템플릿

---

.github/workflows/create-jira-issue.yml

[]() [FEAT] 지라 협업 연동 - 이슈 생성
// close #이슈번호
1. 지라 협업 연동 - 이슈 생성
- 지라 협업 연동 - 이슈 생성
- 
-

[FEAT] 지라 협업 연동 - 이슈 생성

---

.github/workflows/close-jira-issue.yml

[]() [FEAT] 지라 협업 연동 - 이슈 닫기
// close #이슈번호
1. 지라 협업 연동 - 이슈 닫기
- 지라 협업 연동 - 이슈 닫기
- 
-

[FEAT] 지라 협업 연동 - 이슈 닫기

---

src/stories/navigater-bar/index.tsx
yarn.lock

Navbar Image 경로 수정
// close #이슈번호
1. 
- 무비로그 이미지 절대 경로로 수정
- 
-

[FIX] Navbar Image 경로 수정

---

.github/workflows/main.yml

[FIX] CI/CD 오류 수정
1. CI/CD 오류 수정
- CI/CD 오류 해결

[FIX] CI/CD 오류 수정

---

src/pages/recommendations/index.styles.tsx
src/pages/recommendations/index.tsx
src/routers/Router.tsx

[FEAT] 개인 영화 추천 페이지 구현
UP-99
// close #이슈번호
1. 회원가입 때 받은 정보 기반(좋아하는 장르, 좋아하는 영화)으로 사용자에게 맞는 영화 추천
- 
- 
- <img width="337" alt="스크린샷 2024-12-03 17 34 48" src="https://github.com/user-attachments/assets/0870e9e6-a3e8-435f-954b-c33d48ac1f0e">

[FEAT] 개인 영화 추천 페이지 구현

---

src/routers/Router.tsx

[UP-124](https://multicampusuplus.atlassian.net/browse/UP-124)
// close #이슈번호
1. 라우트 분리
- 
- 
-

[FIX]  Routes Path 수정

---

src/pages/main/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

[FIX] Main Page Error 확인 - Test 01

---

src/pages/main/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

[FIX] GenresMovie 컴포넌트 주석 처리

---

src/pages/movie-detail/index.tsx
src/pages/my/components/logout-modal/index.styles.tsx
src/pages/my/components/logout-modal/index.tsx
src/pages/my/index.styles.tsx
src/pages/my/index.tsx
src/stories/button/index.styles.tsx
src/stories/modal/index.styles.tsx

2차 QA 마이페이지 모달창, 커서, 게시글 수정
// close #89
1. 
- 2차 QA 수정
- navigate 수정
- 마이페이지 모달창 수정, 팔로우 버튼 커서 추가
- 리뷰 -> 게시글로 텍스트 수정
- 
-

[FIX] 2차 QA 마이페이지 모달창, 커서, 게시글 수정

---

src/pages/picky/main/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: Playlist 컴포너트 주석 처리

---

src/pages/picky/main/components/playlist/index.tsx
src/pages/picky/main/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: Playlist map method 에러 수정

---

src/pages/admin/operation/movie/movies/components/register-section/index.tsx
src/recoil/selectors/genresSelector.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

Up 127 fix/seo upadte

---

src/pages/login/oauth.tsx
src/pages/signup/components/favorite-movie/index.tsx
src/pages/signup/components/nick-name/index.tsx
src/pages/signup/index.tsx

[FIX] api 호출 주소 변경
// close #이슈번호
1. 
- 
- 
-

[FIX] api 호출 주소 변경

---

src/pages/login/oauth.tsx

fix: 경로 수정
// close #이슈번호
1. 
- 
- 
-

fix: 경로 수정

---

src/pages/login/oauth.tsx
src/pages/search/index.styles.tsx
src/pages/signup/components/consent-form/index.styles.ts
src/pages/signup/components/consent-form/index.tsx
src/pages/signup/components/favorite-genre/index.tsx
src/pages/signup/components/favorite-movie/index.tsx
src/pages/signup/components/nick-name/index.tsx
src/pages/signup/components/profile/index.styles.tsx
src/pages/signup/components/profile/index.tsx
src/pages/signup/index.tsx
src/pages/social/edit/index.styles.ts
src/pages/social/edit/index.tsx

[FIX] 소셜 로그인 주소 변경
// close #이슈번호
1. 
- 
- 
-

[FIX] 소셜 로그인 주소 변경

---

src/mocks/handlers/review/index.ts
src/pages/main/index.tsx
src/pages/signup/components/favorite-movie/index.tsx
src/pages/signup/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

Up 131 feat/create mocking object

---

src/pages/signup/components/nick-name/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: Nickname Authorization 추가

---

src/pages/edit/index.styles.ts
src/pages/edit/index.tsx
src/pages/search/index.styles.tsx
src/pages/signup/components/favorite-genre/index.tsx
src/pages/signup/components/profile/index.styles.tsx
src/pages/signup/components/profile/index.tsx

[FIX] 2차 QA 수정
// close #이슈번호
-  회원가입 (장르) 페이지 최대 5개만 선택 할 수 있도록 수정
- 회원가입 (프로필) 사용하지 않는 코드 정리
- 검색 페이지 레이아웃 수정
- 프로필 수정 페이지 유효성 검사 및 중복 체크 API 연결
- 검색 페이지 필터부분 → cursor: pointer로 변경
- 프로필 수정 버튼 범위 수정
- 
- 
4-12-08 11 01 50" src="https://github.com/user-attachments/assets/ad93ccbe-0d87-4b41-ae1a-edf42677d3b9">

[FIX] 2차 QA 수정

---

src/pages/edit/index.tsx
src/pages/signup/index.tsx
src/routers/Router.tsx

[FIX] 회원가입 페이지 & 개인 프로필 수정 API 수정
// close #이슈번호
1. 
- 회원가입 성공할 시 메인 페이지로 이동
- 프로필 수정 페이지 (닉네임 중복 체크, 유저 조회) api 연결
- 
-

[FIX] 회원가입 페이지 & 개인 프로필 수정 API 수정

---

src/pages/login/index.tsx
src/pages/movie-detail/components/movie-review/index.tsx
src/pages/movie-detail/reviews/components/review-graph/index.tsx
src/pages/movie-detail/reviews/components/review-regist/index.tsx
src/pages/movie-detail/reviews/index.tsx

[]()
// close #135
1. 한줄평 POST API 연동
- 
- 
-

[FEAT] 한줄평 POST API 연동

---

src/pages/login/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: Social Login Button 분리

---

.github/workflows/main.yml

[UPDATE] env 파일 추천
// close #이슈번호
1. 
- 
- 
-

[UPDATE] env 파일 추천

---

.github/workflows/main.yml

[FIX]Update main.yml
// close #이슈번호
1. .env 파일 수정
- 
- 
-

[FIX]Update main.yml

---

src/mocks/handlers/board/index.ts
src/pages/main/index.tsx

[UP-131](https://multicampusuplus.atlassian.net/browse/UP-131)
// close #111 
1. 
- 게시물 좋아요 추가, 취소 하나의 컨틀롤러로 수정
- 
-

[FIX] 게시물 좋아요 취소, 추가 하나 Controller에서 해결

---

src/pages/edit/index.tsx
src/pages/recommendations/index.tsx

[FEAT] 추천 페이지 API 연결
// close #이슈번호
1.  추천 페이지 API 연결
- 
- 
-

[FEAT] 추천 페이지 API 연결

---

src/pages/recommendations/index.tsx

[FIX] 영화 추천 페이지 API 수정
// close #이슈번호
1. 
- 영화 추천 페이지 API 수정
- 
-

[FIX] 영화 추천 페이지 API 수정

---

src/pages/social/feed/index.styles.ts
src/pages/social/feed/index.tsx
src/pages/social/post/index.tsx

[FEAT] 무비로그 CRD API 연결
// close #134 
1. 모든 무비로그 조회 기능 구현
2. 무비로그 생성 기능 구현 (약간 빈약한데 이건 좀 수정해야 할 듯)
3. 무비로그 삭제 기능 구현

[FEAT] 무비로그 CRD API 연결

---

src/pages/recommendations/index.tsx

[FIX] 영화 추천 페이지 수정
// close #이슈번호
1. 
- 수정
- 
-

[FIX] 영화 추천 페이지 수정

---

src/pages/recommendations/index.styles.tsx
src/pages/recommendations/index.tsx

[]()
// close #이슈번호
1. 
- 영화 추천 페이지
- 
-

[FIX] 영화 추천 페이지

---

src/pages/recommendations/index.tsx
src/stories/movie-item/index.tsx

[FIX] 영화 추천 페이지 수정 및 스토리북 수정
// close #이슈번호
1. 
- 영화 추천 페이지 수정 및 스토리북 수정
- 
-

[FIX] 영화 추천 페이지 수정 및 스토리북 수정

---

src/pages/edit/index.tsx

[FIX] 유저 프로필 수정 페이지 수정
// close #이슈번호
1. 
- 유저 프로필 수정 페이지 수정
- 
-

[FIX] 유저 프로필 수정 페이지 수정

---

src/mocks/handlers/board/index.ts
src/pages/google/index.tsx
src/pages/social/comment/index.tsx
src/pages/social/feed/index.tsx
src/routers/Router.tsx

[FEAT] 무비로그 상세 페이지 기능 구현
// close #134 
1. 무비로그 상세 조회 기능 구현
2. 무비로그 댓글 조회 API 연결
3. 무비로그 댓글 삭제 API 연결
4. 무비로그 댓글 생성 API 연결
5. 특정 영화 무비로그 조회 기능 구현

[FEAT] 무비로그 상세 페이지 기능 구현

---

src/pages/social/feed/index.tsx
src/pages/social/modify/index.styles.ts
src/pages/social/modify/index.tsx
src/pages/social/post/index.tsx
src/routers/Router.tsx

[FIX] 무비로그 API 수정
// close #179 
1. 무비로그 조회 api 수정
2. 무비로그 삭제 api 수정

[FIX] 무비로그 API 수정

---

src/pages/edit/index.tsx

[FIX] 개인 프로필 수정 페이지에 이메일 내용 추가
// close #이슈번호
1.  이메일 정보 추가
- 
- 
-

[FIX] 개인 프로필 수정 페이지에 이메일 내용 추가

---

src/pages/my/components/tab-menu/review/index.tsx

마이페이지 한줄평 포스터 수정
// close #156
1. 마이페이지 한줄평 포스터 수정
- 
- 
-

[FIX] 마이페이지 한줄평 포스터 수정

---

src/pages/login/index.styles.tsx
src/pages/login/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: Login Style 수정

---

src/pages/signup/components/user-name/index.tsx

[FIX] 회원가입 페이지 버그 수정
// close #이슈번호
1. 회원가입 페이지 이름 입력 안되는 버그 수정
- 회원가입 페이지 이름 입력 안되는 버그 수정
- 
-

[FIX] 회원가입 페이지 버그 수정

---

package.json
src/pages/login/index.tsx
src/pages/login/naver/oauth.tsx
yarn.lock

[FIX] 소셜 로그인 받아오는 토큰 값들 쿠키에 저장
// close #이슈번호
1. 
- 
- 
-

[FIX] 소셜 로그인 받아오는 토큰 값들 쿠키에 저장

---

src/pages/login/naver/oauth.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: CurrerUserCookie 출력

---

src/pages/login/naver/oauth.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: log 추가

---

src/pages/login/naver/oauth.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: JSON 수정

---

src/api/index.ts
src/api/movie/index.ts
src/hooks/movie/index.tsx
src/mocks/handlers/movie/index.ts
src/pages/main/components/famous-movie/index.tsx
src/pages/main/components/recommend-slider/index.styles.tsx
src/pages/main/components/recommend-slider/index.tsx
src/pages/main/index.tsx
src/stories/movie-item/index.styles.tsx
src/stories/movie-item/index.tsx
src/types/api/movie/index.d.ts

[]()
// close #이슈번호
1. 
- 
- 
-

Up 169 feat/top 10 movie

---

src/api/index.ts
src/api/user/index.ts
src/pages/signup/components/nick-name/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

Up 139 feat/signup fix

---

src/pages/signup/components/nick-name/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: await로 수정

---

src/api/user/index.ts
src/components/genre/index.tsx
src/pages/signup/components/favorite-movie/index.tsx
src/pages/signup/components/nick-name/index.tsx
src/recoil/selectors/genresSelector.tsx
src/review/atoms.ts

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 영화 불러오기 수정

---

src/api/index.ts
src/api/user/index.ts
src/pages/signup/components/favorite-movie/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: Merge branch 'dev' into UP-139-feat/signup-fix

---

src/pages/login/naver/oauth.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: Cookie 시간 증가

---

src/pages/signup/components/favorite-movie/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 영화 페이지 수정

---

src/api/user/index.ts
src/pages/signup/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 회원가입 컴플리트 API 수정

---

src/pages/login/index.tsx
src/pages/login/naver/oauth.tsx
src/pages/main/components/famous-movie/index.tsx
src/pages/main/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: Object object 단순 문자열 해결

---

src/pages/login/naver/oauth.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 영구 쿠키에서 세션 쿠키로 수정

---

src/pages/main/components/famous-movie/index.tsx
src/stories/movie-item/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: Movie Image src 수정 (#197)

---

src/pages/login/naver/oauth.tsx
src/recoil/selectors/useAuthorization.ts
src/routers/Router.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 로그인 상태 유지

---

src/pages/login/naver/oauth.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 로그인 User Cookie 정보 수정

---

src/api/user/index.ts
src/pages/login/naver/oauth.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: User GET API 모듈로 분리

---

src/components/navbar/index.tsx
src/mocks/handlers/auth/index.ts
src/mocks/handlers/board/index.ts
src/mocks/handlers/movie/index.ts
src/mocks/handlers/review/index.ts
src/pages/login/naver/oauth.tsx
src/pages/signup/index.tsx
src/stories/movie-item/index.tsx

[UP-169](https://multicampusuplus.atlassian.net/browse/UP-169)
// close #197 
1. Axios -> 초기 설정 + 인터셉터 설정
2. Top 10 Movie API 연동
3. MSW 수정
4. 네이버 로그인 Cookie 수정
5. sessionStorage -> Cookie 수정
- 
- 
-

[FEAT] TOP 10 Movie && MSW Update && Social Login Update && SessionStorage -> Cookie Update

---

src/api/index.ts
src/api/user/index.ts
src/pages/edit/index.tsx
src/pages/login/naver/oauth.tsx
src/pages/signup/index.tsx

[REFACTOR]회원가입 및 프로필 수정 데이터 전송 및 검증 로직 개선
// close #이슈번호
1. 
- 회원가입 및 프로필 수정 시 단계별 검증 로직(isStepValid) 리팩토링
- Enter 키 이벤트 처리 로직 최적화 및 중복 방지 로직 추가
- FormData 생성 시 JSON 데이터와 파일 처리 방식 통일
- 프로필 수정 페이지에서 닉네임 및 이미지 변경 시의 유효성 검증 강화
- 
-

[REFACTOR]회원가입 및 프로필 수정 데이터 전송 및 검증 로직 개선

---

src/pages/edit/index.tsx

[FIX]유저 정보 요청 로그 추가
// close #이슈번호
1. 유저 정보 요청 로그 추가
- 
- 
-

[FIX]유저 정보 요청 로그 추가

---

src/pages/login/naver/oauth.tsx

[FIX] 유저 정보 호출
// close #이슈번호
1.  [FIX] 유저 정보 로그 추가
- 
- 
-

[FIX] 유저 정보 호출 로그 추가

---

src/pages/edit/index.tsx
src/pages/login/naver/oauth.tsx

[FIX] 프로필 수정 페이지 버그 수정
// close #이슈번호
1. 
- 프로필 수정 페이지 버그 수정
- 
-

[FIX] 프로필 수정 페이지 버그 수정

---

src/pages/login/google/oauth.tsx
src/pages/login/kakao/oauth.tsx

[FIX] 소셜로그인 구글 카카오 쿠키 정보 등록 적용
// close #이슈번호
1. 로그인 한 유저 정보 쿠키에 저장
- 
- 
-

[FIX] 소셜로그인 구글 카카오 쿠키 정보 등록 적용

---

src/components/layout/index.tsx
src/components/navbar/index.tsx
src/mocks/handlers/auth/index.ts
src/mocks/handlers/board/index.ts
src/mocks/handlers/movie/index.ts
src/mocks/handlers/review/index.ts
src/pages/login/index.tsx
src/pages/login/naver/oauth.tsx
src/pages/main/components/recommend-slider/index.tsx
src/pages/main/index.tsx
src/pages/recommendations/index.tsx
src/pages/signup/index.tsx
src/recoil/atoms/isLoginState.ts
src/routers/Router.tsx
src/stories/movie-item/index.tsx
src/types/api/movie/index.d.ts

[UP-173](https://multicampusuplus.atlassian.net/browse/UP-173)
// close #226 
1. 추천 데이터 API 호출
2. 추천 데이터 데이터 캐싱
3. 메인 페이지 추천 데이터 개수에 따른 슬라이드 수정
4. 추천 페이지 API 수정
- 
- 
-

[FEAT] 추천 데이터 API 연동 및 추천 페이지 수정

---

src/pages/login/google/oauth.tsx
src/routers/Router.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 구글 인증 경로 수정

---

src/pages/login/google/oauth.tsx

fix: 구글 소셜 로그인
// close #이슈번호
1. 
- 
- 
-

fix: 구글 소셜 로그인

---

src/api/movie/index.ts
src/components/genre/index.tsx
src/constants/json/user.json
src/hooks/movie/index.tsx
src/mocks/handlers/movie/index.ts
src/pages/main/components/famous-movie/index.tsx
src/pages/main/components/genres-movie/index.tsx
src/stories/movie-item/index.styles.tsx
src/stories/movie-item/index.tsx
src/types/api/movie/index.d.ts

[UP-179](https://multicampusuplus.atlassian.net/browse/UP-179)
// close #235 
1. 장르별 영화 조회 API 초기 설정
2. 장르별 영화 조회 React Query 초기 설정
3. 
- 메인 페이지 - 장르 버튼 클릭 시 액티브 활성화로 수정
- 장르 영화 클릭 시 영화 상세 페이지 이동
- Movie Item 영화 제목 줄바꿈 처리 수정
- 
-

[FEAT] 장르별 영화 1차 PR

---

src/components/seo/index.tsx
src/pages/main/components/genres-movie/index.tsx
src/pages/picky/genre-detail/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

Up 179 feat/genre movie

---

src/mocks/browser.ts
src/mocks/handlers/movie/index.ts
src/pages/main/components/recommend-slider/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 에러 수정

---

src/pages/edit/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 프로필 수정 페이지 디자인 수정

---

src/pages/edit/index.styles.ts
src/pages/edit/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 디자인 수정

---

src/pages/main/components/genres-movie/index.tsx
src/pages/picky/main/components/playlist/index.tsx
src/stories/movie-item/index.styles.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 장르 영화 주석 처리

---

src/pages/main/components/genres-movie/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

test: 장르 영화 출력

---

src/pages/picky/genre-detail/index.tsx
src/stories/movie-item/index.styles.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: Movie Item 높이 수정 (#235)

---

src/pages/picky/genre-detail/index.styles.tsx
src/pages/picky/genre-detail/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 무한 스크롤 수정 중 (#235)

---

src/hooks/movie/index.tsx
src/pages/main/components/genres-movie/index.styles.tsx
src/pages/picky/genre-detail/index.styles.tsx
src/pages/picky/genre-detail/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 장르 영화 무한 스크롤링 적용

---

src/constants/routes/routeConfig.ts
src/provider/QueryProvider.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 데이터 조회

---

src/api/movie/index.ts
src/constants/json/genres/movieAndGenre.json
src/pages/picky/genre-detail/index.tsx
src/provider/QueryProvider.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

test: 출력 추가

---

src/api/movie/index.ts
src/hooks/movie/index.tsx
src/pages/movie-detail/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

test: 무비 디테일 콘솔

---

src/api/linereview/index.ts
src/components/seo/index.tsx
src/hooks/review/index.ts
src/mocks/handlers/review/index.ts
src/pages/movie-detail/components/movie-footer/index.styles.tsx
src/pages/movie-detail/components/movie-info/index.tsx
src/pages/movie-detail/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: Movie Detail 수정

---

src/api/playlist/index.ts
src/constants/json/line-review/lineReviewLikes.json
src/hooks/playlist/index.ts
src/mocks/handlers/movie/index.ts
src/mocks/handlers/movie/playlist/index.ts
src/mocks/handlers/review/index.ts
src/pages/login/index.tsx
src/pages/picky/genre-detail/index.tsx
src/pages/picky/main/components/best-movies/index.tsx
src/pages/picky/main/components/movie-backdrop-banner/index.tsx
src/pages/picky/main/components/playlist/index.styles.tsx
src/pages/picky/main/components/playlist/index.tsx
src/pages/picky/main/index.tsx

[]()
// close #264 
1. Playlist API 설계
2. Playlist 데이터 React Query를 통한 데이터 캐싱
3. Picky Page - Playlist 커서 기반 무한스크롤링 기법 적용
- 
- 
-

[FEAT] Picky page - Playlist 커서 기반 무한 스크롤링 적용

---

src/pages/login/google/oauth.tsx
src/pages/login/kakao/oauth.tsx
src/pages/login/naver/oauth.tsx

[FIX] 쿠키 담는 정보 수정
// close #이슈번호
1. 쿠키에 담는 정보 변경
- 
- 
-

[FIX] 쿠키 담는 정보 수정

---

src/api/movie/index.ts
src/api/playlist/index.ts
src/components/header/index.tsx
src/components/pages/admin/info/index.tsx
src/constants/header/index.tsx
src/constants/json/movie/platform.json
src/constants/routes/routeConfig.ts
src/hooks/movie/index.tsx
src/mocks/handlers/movie/index.ts
src/pages/admin/main/index.styles.tsx
src/pages/admin/operation/movie/movies/components/register-section/index.styles.tsx
src/pages/admin/operation/movie/movies/components/register-section/index.tsx
src/pages/admin/operation/movie/movies/index.styles.tsx
src/recoil/atoms/isLoginState.ts
src/recoil/selectors/useAuthorization.ts
src/stories/header/Header.stories.tsx
src/stories/header/index.styles.tsx
src/stories/header/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

[FEAT] 영화 등록 API 구성

---

src/api/movie/index.ts
src/mocks/browser.ts
src/mocks/handlers/auth/index.ts
src/pages/admin/operation/movie/movies/components/register-section/index.tsx
src/pages/login/index.tsx
src/pages/social/comment/index.styles.ts
src/pages/social/comment/index.tsx
src/pages/social/feed/index.tsx
src/pages/social/post/index.tsx

[FIX] 무비로그 페이지 api 수정
// close #이슈번호
1. 무비로그 페이지 api 수정

[FIX] 무비로그 페이지 api 수정

---

src/api/movie/index.ts
src/mocks/handlers/auth/index.ts
src/pages/social/comment/index.styles.ts
src/pages/social/comment/index.tsx

[FIX] 무비로그 상세 댓글 api 수정
// close #이슈번호
1. 무비로그 상세 댓글 api 수정

[FIX] 무비로그 상세 댓글 api 수정

---

src/api/youtube/index.ts
src/mocks/handlers/movie/index.ts
src/pages/login/index.tsx
src/pages/movie-detail/components/behind-modal/index.tsx
src/pages/movie-detail/index.tsx
src/pages/movie-detail/reviews/components/review-graph/index.tsx
src/pages/movie-detail/reviews/index.tsx
src/pages/my/index.tsx

youtube data api 오류 수정 & 마이페이지 쿠키 제거 & 영화 상세페이지 SEO 오류 수정
// close #이슈번호
1. 
-  마이페이지-쿠키 빼고 수정
- 영화상세페이지-SEO/영화제목/출연제작 이름 안 보이는 거 해결
- YouTube DATA API 오류 수정
- 
-

[FIX] youtube data api 오류 수정 & 마이페이지 쿠키 제거 & 영화 상세페이지 SEO 오류 수정

---

.github/workflows/main.yml
src/api/movie/index.ts
src/mocks/handlers/auth/index.ts
src/pages/social/feed/index.tsx
src/pages/social/modify/index.tsx
src/pages/social/post/index.tsx

[FEAT] 무비로그 수정 기능 및 환경변수 설정
// close #이슈번호
1. 무비로그 수정 기능 및 환경변수 설정

[FEAT] 무비로그 수정 기능 및 환경변수 설정

---

src/mocks/handlers/board/index.ts

[]()
// close #이슈번호
1. 
- 
- 
-

fix: board isAuthor 추가

---

src/pages/social/feed/index.tsx

[FIX] 무비로그 삭제 수정
// close #이슈번호
1. 무비로그 삭제 수정

[FIX] 무비로그 삭제 수정

---

src/pages/edit/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 프로필 수정 페이지 수정

---

src/pages/my/index.tsx

[]()
// close #이슈번호
1. 
- 배포 환경에서 마이페이지 오류로 코드 수정
- 
-

[FIX] 마이페이지 API 연동 코드 수정

---

src/pages/my/components/tab-menu/review/index.tsx

마이페이지 api 연동 4차 PR
// close #이슈번호
1. 
- 한줄평 클릭시 이동 에러 해결
- 
-

[FIX] 마이페이지 api 연동 4차 PR

---

vite.config.ts

[]()
// close #이슈번호
1. 
- 
- 
-

fix: prerender 수정

---

src/components/seo/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 오픈 그래프 이미지 경로 수정

---

src/api/linereview/index.ts
src/pages/my/components/tab-menu/review/index.tsx

마이페이지 한줄평 api 연동 5차 PR
// close #이슈번호
1. 
- 마이페이지 한줄평 조회 GET API 연동
- 
-

[FIX] 마이페이지 한줄평 api 연동 5차 PR

---

src/components/seo/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 이미지 경로 수정

---

src/api/user/index.ts
src/pages/search/index.styles.tsx
src/pages/search/index.tsx

[FEAT] 검색 페이지 API 연결 및 디자인 수정
// close #이슈번호
1. 검색 페이지 API 연결 
2. 디자인 수정
- 
- 
- <img width="383" alt="스크린샷 2024-12-16 14 01 08" src="https://github.com/user-attachments/assets/6329f575-96dd-4b5c-ae4c-6b7e7adf1304" />

[FEAT] 검색 페이지 API 연결 및 디자인 수정

---

src/mocks/handlers/auth/index.ts
src/pages/login/index.tsx
src/pages/social/comment/index.tsx

[FIX] 무비로그 댓글 삭제 api 수정
// close #이슈번호
1. 무비로그 댓글 삭제 api 수정

[FIX] 무비로그 댓글 삭제 api 수정

---

src/api/linereview/index.ts
src/api/movie/index.ts
src/pages/my/components/tab-menu/index.tsx
src/pages/my/components/tab-menu/movie-log/index.tsx
src/pages/social/post/index.styles.ts
src/pages/social/post/index.tsx
src/stories/file-input/components/media/index.tsx
src/stories/file-input/index.tsx

[FIX] 마이페이지 무비로그 탭 api 연결
// close #이슈번호
1. 마이페이지 무비로그 탭 api 연결

[FIX] 마이페이지 무비로그 탭 api 연결

---

src/api/movie/index.ts

[FIX] 무비로그 생성 수정
// close #이슈번호
1. 무비로그 생성 수정

[FIX] 무비로그 생성 수정

---

src/api/movie/index.ts
src/pages/social/post/index.tsx

[FIX] 무비로그 등록 수정
// close #이슈번호
1. 무비로그 등록 수정

[FIX] 무비로그 등록 수정

---

src/api/playlist/index.ts
src/pages/admin/operation/movie/playlists/index.tsx

[]()
// close #이슈번호
1. 등록 가능한 플레이 리스트 조회 성공
2. 플레이 리스트 등록 (안됨)
3. 플레이 리스트 수정 (안됨)
4. 플레이 리스트 삭제 (안됨)
- 모든 api 는 연결했습니다.
- 
-

[FEAT] 관리자 플레이 리스트 기능 추가

---

src/api/index.ts
src/api/movie/index.ts
src/hooks/movie-log/index.ts
src/mocks/handlers/auth/index.ts
src/pages/social/feed/index.tsx
src/pages/social/post/index.tsx

[FEAT] 무비로그 생성 & 무한스크롤 구현
// close #이슈번호
1. 무비로그 생성 구현
2. 무한스크롤 구현

[FEAT] 무비로그 생성 & 무한스크롤 구현

---

src/api/movie/index.ts
src/pages/my/components/tab-menu/index.tsx
src/pages/my/components/tab-menu/movie-log/index.tsx

[FEAT] 마이페이지 무비로그 조회 구현
// close #이슈번호
1. 마이페이지 무비로그 조회 구현

[FEAT] 마이페이지 무비로그 조회 구현

---

src/api/user/index.ts

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 토큰 수정

---

src/api/notification/index.ts
src/components/header/index.tsx
src/components/navbar/index.tsx
src/hooks/notification/connect/badge.ts
src/pages/main/index.tsx
src/pages/notification/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: react hook 오류 수정

---

src/constants/json/user.json
src/mocks/handlers/auth/index.ts
src/pages/login/index.tsx
src/pages/my/components/tab-menu/movie-log/index.styles.tsx
src/pages/my/components/tab-menu/movie-log/index.tsx

[FEAT] 마이페이지 무비로그 구현
// close #이슈번호
1.  마이페이지 무비로그 구현

[FEAT] 마이페이지 무비로그 구현

---

src/api/user/index.ts

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 버그 수정

---

src/pages/signup/components/favorite-movie/index.tsx
src/pages/signup/components/profile/index.tsx

[FIX]회원 가입시 기본 이미지 설정을 했을경우 기본 이미지 formada로 서버에 전송
// close #이슈번호
1. 회원 가입시 기본 이미지 설정을 했을경우 기본 이미지 formada로 서버에 전송
- 
- 
-

[FIX]회원 가입시 기본 이미지 설정을 했을경우 기본 이미지 formada로 서버에 전송

---

src/components/layout/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 쿠키 수정

---

src/api/user/index.ts
src/components/layout/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 쿠키 삭제 수정

---

src/api/user/index.ts

[]()
// close #이슈번호
1. 
- 
- 
-

fix: User GET API 수정

---

src/api/user/index.ts

[]()
// close #이슈번호
1. 
- 
- 
-

fix: Login

---

src/api/user/index.ts

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 닉네임 중복 체크 수정

---

src/mocks/browser.ts
src/pages/my/components/tab-menu/movie-log/index.tsx
src/pages/social/feed/index.styles.ts
src/pages/social/feed/index.tsx
src/stories/movie-log/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

[FIX] QA 사항 수정

---

src/pages/edit/index.tsx

[FIX] 프로필 수정 페이지 기본 이미지 설정 적용
// close #이슈번호
1. 
- 프로필 수정 페이지 기본 이미지 설정 적용
- 
-

[FIX] 프로필 수정 페이지 기본 이미지 설정 적용

---

src/mocks/handlers/auth/index.ts
src/pages/login/index.tsx
src/pages/social/comment/index.tsx
src/pages/social/feed/index.tsx

[FIX] 무비로그 댓글 삭제 기능 수정
// close #이슈번호
1. 무비로그 댓글 삭제 기능 수정

[FIX] 무비로그 댓글 삭제 기능 수정

---

src/api/movie/index.ts
src/pages/social/comment/index.tsx

[FIX] 댓글 삭제 기능 수정
// close #이슈번호
1.  댓글 삭제 기능 수정

[FIX] 댓글 삭제 기능 수정

---

src/api/movie/index.ts
src/constants/json/user.json
src/hooks/movie-log/index.ts
src/pages/social/comment/index.tsx
src/pages/social/modify/index.tsx
src/pages/social/movie-feed/index.tsx
src/stories/movie-log/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 무비로그 api 수정

---

src/api/user/index.ts
src/mocks/handlers/movie/index.ts
src/pages/edit/index.tsx
src/pages/search/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

[FEAT] 에라스틱 검색 API 적용

---

src/pages/search/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 검색페이지 배우 제거

---

src/pages/google/google.tsx
src/pages/search/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 색상 메인 컬러

---

src/mocks/handlers/auth/index.ts
src/pages/movie-detail/components/movie-info/index.styles.tsx
src/pages/social/movie-feed/index.tsx
src/pages/social/post/index.tsx

fix: 기능 수정
// close #이슈번호
1. 기능 수정

fix: 기능 수정

---

src/pages/social/modify/index.styles.ts
src/pages/social/modify/index.tsx
src/pages/social/movie-feed/index.tsx
src/pages/social/post/index.styles.ts
src/pages/social/post/index.tsx

fix: 무비로그 수정
// close #이슈번호
1. 무비로그 수정

fix: 무비로그 수정

---

src/mocks/handlers/auth/index.ts
src/pages/my/components/tab-menu/movie-log/index.tsx
src/pages/social/comment/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 프로필 페이지에서 무비로그 상세 페이지로 이동 수정

---

src/mocks/handlers/auth/index.ts
src/pages/login/index.tsx
src/pages/social/comment/index.styles.ts
src/pages/social/comment/index.tsx
src/pages/social/post/index.tsx

[FIX] 무비로그 상세 페이지 완성
// close #이슈번호
1. 무비로그 상세 페이지 완성

[FIX] 무비로그 상세 페이지 완성

---

src/App.tsx
src/components/splash-screen/index.styles.tsx
src/components/splash-screen/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

feat: splash_screen

---

src/mocks/handlers/auth/index.ts
src/pages/login/index.tsx
src/pages/social/comment/index.tsx
src/pages/social/feed/index.styles.ts
src/pages/social/feed/index.tsx
src/pages/social/movie-feed/index.tsx
src/pages/social/post/index.tsx

[FIX] 수정 사항 적용
// close #이슈번호
1. 수정 사항 적용
- 
- 
-

[FIX] 수정 사항 적용

---

src/pages/social/comment/index.tsx
src/pages/social/feed/index.styles.ts
src/pages/social/feed/index.tsx
src/pages/social/movie-feed/index.tsx
src/pages/social/post/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

Up 158 fix/movielog api

---

src/pages/social/comment/index.tsx
src/pages/social/movie-feed/index.tsx

[FIX] 게시글 생성 시간 수정
// close #이슈번호
1. 게시글 생성 시간 수정

[FIX] 게시글 생성 시간 수정

---

eslint.config.js
package-lock.json
src/components/seo/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: open graph

---

src/api/playlist/index.ts
src/pages/admin/operation/movie/playlists/components/modal/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: playlist 바로 반영 완료 (#349)

---

src/hooks/notification/connect/badge.ts
src/hooks/notification/connect/index.ts
src/hooks/notification/fetch/index.ts
src/pages/main/index.tsx
src/pages/my/components/logout-modal/index.tsx
src/pages/social/post/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 출력 제거

---

src/pages/movie-detail/components/movie-rating/index.tsx

[]()
// close #이슈번호
1. 
- 
- 
-

fix: 좋아요한 영화 업데이트
